"""Lazy, version-pinned AIConfigurator SDK adapter."""

import importlib.metadata
import math
import shutil
import struct
import tempfile
from collections.abc import Mapping
from pathlib import Path
from typing import Any
from uuid import uuid4

from portal.adapters import ConfigurationRow, RunRequest, RunResult, VisualizationAsset
from portal.tradeoff import normalize_tradeoff_surface

_PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def _scalar(value: Any) -> float | int | str | None:
    """Convert a DataFrame cell into a JSON-safe scalar."""

    if value is None:
        return None
    if hasattr(value, "item"):
        value = value.item()
    if isinstance(value, float) and math.isnan(value):
        return None
    if isinstance(value, (bool, float, int, str)):
        return value
    return str(value)


def _normalize_rows(best_configs: Mapping[str, Any]) -> tuple[ConfigurationRow, ...]:
    """Normalize SDK DataFrames without exposing nested diagnostic payloads."""

    rows: list[ConfigurationRow] = []
    for mode, frame in best_configs.items():
        for index, record in enumerate(frame.to_dict(orient="records"), start=1):
            metrics = {
                str(key): normalized
                for key, value in record.items()
                if key != "_per_ops_source" and (normalized := _scalar(value)) is not None
            }
            rows.append(ConfigurationRow(rank=index, serving_mode=str(mode), metrics=metrics))
    return tuple(rows)


def _discover_pareto_frontier(root: Path) -> tuple[VisualizationAsset, ...]:
    """Return one verified SDK PNG, or no visualization when output is ambiguous."""

    candidates = sorted(path for path in root.rglob("pareto_frontier.png") if path.is_file())
    if len(candidates) != 1:
        return ()
    candidate = candidates[0]
    if candidate.is_symlink():
        return ()
    try:
        relative_path = candidate.relative_to(root).as_posix()
        resolved_path = candidate.resolve()
        if not resolved_path.is_relative_to(root.resolve()):
            return ()
        header = candidate.read_bytes()
        if len(header) < 24 or header[:8] != _PNG_SIGNATURE:
            return ()
        width, height = struct.unpack(">II", header[16:24])
    except (OSError, ValueError, struct.error):
        return ()
    if width < 1 or height < 1:
        return ()
    return (
        VisualizationAsset(
            asset_id=uuid4().hex,
            relative_path=relative_path,
            media_type="image/png",
            width=width,
            height=height,
            alt_text=(
                "AIConfigurator Pareto frontier visualization from the completed "
                "serving-configuration sweep."
            ),
            caption="AIConfigurator Pareto frontier from this completed sweep.",
            scope_note=(
                "This is the dependency-generated frontier for the same full sweep; it is not "
                "recomputed from the displayed top-N rows."
            ),
            axis_note=(
                "Axes and labels are generated by AIConfigurator; use the ranked table below "
                "for exact numeric values."
            ),
        ),
    )


def run_ai_configurator(request: RunRequest, output_dir: str) -> RunResult:
    """Run one default sweep in a worker process.

    The import is intentionally inside the function: the published dependency is
    Linux x86-64 only and must not be imported by local ARM development tools.
    """

    from aiconfigurator.cli import cli_default  # type: ignore[import-not-found]

    destination = Path(output_dir)
    destination.mkdir(parents=True, exist_ok=True)
    # AIConfigurator's safe_mkdir intentionally restricts output roots to
    # approved prefixes (including /tmp). Stage there, then copy the generated
    # tree into the portal-owned per-run directory.
    with tempfile.TemporaryDirectory(prefix="portal-aiconfigurator-") as staging:
        result = cli_default(
            model_path=request.model,
            total_gpus=request.total_gpus,
            system=request.system,
            ttft=request.ttft_ms,
            tpot=request.tpot_ms,
            isl=request.isl,
            osl=request.osl,
            strict_sla=True,
            top_n=5,
            save_dir=staging,
        )
        shutil.copytree(staging, destination, dirs_exist_ok=True)
    package_version = importlib.metadata.version("aiconfigurator")
    return RunResult(
        rows=_normalize_rows(result.best_configs),
        artifact_dir=destination,
        source_version=f"aiconfigurator-{package_version}",
        visualizations=_discover_pareto_frontier(destination),
        tradeoff_surface=normalize_tradeoff_surface(result.pareto_fronts),
    )
