apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alloy.yaml

configMapGenerator:
  - name: portal-alloy-config
    files:
      - config.alloy=alloy.config.alloy
    options:
      disableNameSuffixHash: true
  - name: portal-grafana-datasources
    files:
      - datasources.yaml=grafana/provisioning/datasources/datasources.yaml
    options:
      disableNameSuffixHash: true
